name: moneyup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  supabase_flutter: ^2.12.0
  percent_indicator: ^4.2.5
  fl_chart: ^1.1.1
  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.2
  form_field_validator: ^1.1.0
  smooth_page_indicator: ^2.0.1
  carousel_slider: ^5.1.2
  shared_preferences: ^2.5.4
  url_launcher: ^6.1.10
  app_links: ^6.4.1
  plaid_flutter: ^5.0.5
  flutter_dotenv: ^6.0.0
  flutter_slidable: ^4.0.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900